### ISSUE TITLE
Cannot find module 'mz/fs'

### ISSUE THREAD

**Issue by froggyman** [domenic/worm-scraper#14]
i ran "worm-scraper --help" and got this error:

> module.js:472
>     throw err;
>     ^
> 
> Error: Cannot find module 'mz/fs'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.Module._load (module.js:418:25)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\Program Files\Node\node_modules\worm-scraper\lib\download.js:3:12)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)

**Comment by domenic** [comment]
It looks like I actually forgot to depend on the `mz` package explicitly. In theory I shouldn't need to, but it's good practice, and I guess maybe on some machines or in some situations it caused issues.

I've released 2.4.0 with an explicit dependency.
