### ISSUE TITLE
Error: ENOENT: no such file or directory, rmdir

### ISSUE THREAD

**Issue by vigneshwar221B** [domenic/worm-scraper#18]
I tried running `worm-scraper download convert scaffold zip` but after downloading the last chapter, it throws the error `Error: ENOENT: no such file or directory, rmdir '/Users/vigneshwar/Desktop/staging/worm/OEBPS/chapters'`

**Comment by domenic** [comment]
Hmm. I can't reproduce this myself. Can you try running it again and seeing what happens? You can probably omit the `download` that time.

**Comment by domenic** [comment]
This might happen if you use a Node.js version below 12.10.0. It looks like the readme says 10.0.0 is the minimum, but that is probably not correct....
