### ISSUE TITLE
`worm-scraper download` hangs after downloading a few chapters

### ISSUE THREAD

**Issue by brachbach** [domenic/worm-scraper#20]
Didn't look into why.

I hacked around it with this fish script:

```
function retryworm
    timeout 10 worm-scraper download
end
```

**Comment by brachbach** [comment]
I ran the script on Node v10.16.3, that might have been the problem

**Comment by domenic** [comment]
Let me know if it gets better on newer Node. However I rarely download in local development, so it's possible the code is not as resilient to transient issues as it should be.

**Comment by domenic** [comment]
I haven't seen this recently, despite a few download runs, so I'll close it for now... The logging has been updated a bit which could help, if it's still an issue.
