### ISSUE TITLE
`ENOENT: no such file or directory, rmdir '/Users/brachbach/worm/staging/worm/OEBPS/chapters'` for `worm-scraper convert`

### ISSUE THREAD

**Issue by brachbach** [domenic/worm-scraper#21]
I didn't have that directory at the point at which I ran `worm-scraper convert` (not sure if I was supposed to somehow have it, or what).

Hacked around it for now by just creating the director manually before running the command.

But I think the script should check whether the directory exists and only attempt to remove it if it does exist

**Comment by domenic** [comment]
Did you follow this part of the instructions in the README?

> First you'll need a modern version of Node.js. Install whatever is current (not LTS); at least v12.10.0 is necessary.

**Comment by brachbach** [comment]
Ah, nope! I'll close this.
