### ISSUE TITLE
Ward build hanging at chapter 16-10

### ISSUE THREAD

**Issue by aes87** [domenic/worm-scraper#25]
Hello—thank you for making this tool.

After finishing worm a while ago, I recently desired to pick up ward.  Unfortunately my book build is failing at chapter 16-10 with the message I will post below.

I installed using the current node.js, 15.6.0 in case that is relevant.

Downloading https://www.parahumans.net/2019/09/15/from-within-16-10/... TypeError: Cannot read property 'textContent' of null
    at getChapterTitle (C:\Users\aes\AppData\Roaming\npm\node_modules\worm-scraper\lib\download.js:93:55)
    at downloadAllChapters (C:\Users\aes\AppData\Roaming\npm\node_modules\worm-scraper\lib\download.js:49:26)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async C:\Users\aes\AppData\Roaming\npm\node_modules\worm-scraper\lib\worm-scraper.js:111:7

**Comment by domenic** [comment]
Thanks! I can reproduce this locally and have a fix. However, it appears some other stuff has happened to the parahumans.net pages that caused this, so I need to fix a few other things first... Look forward to a new release soon.
