### ISSUE TITLE
Issue with running convert.js when no pre-existing "staging" path

### ISSUE THREAD

**Issue by Chocbanana** [domenic/worm-scraper#30]
When running `worm-scraper convert...` , if there is no pre-existing "staging" path (aka upon fresh run), it gives this error:
`(node:6172) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead`
And that means `fs.rmdir` no longer allows for no existing path with the `recursive: true` arg. 

The fix is to simply change line 90  in `worm-scraper.js` to the following:
`return fs.rm(chaptersPath, { force: true, recursive: true, maxRetries: 3 })`
And that made it work for me.

**Comment by gorman42** [comment]
I needed to apply the suggested fix to have the latest version (4.12.1) work for me.
Thanks Chocbanana for sharing it. Much appreciated.
