### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by TheIronRose** [domenic/worm-scraper#4]
As the title says. Installed with v7.4.0 of node.js (not the LTS version) on Windows 10 x64 and ran in an elevated command prompt. 

Running worm-scraper --help prompts a syntax error (Code: 800A03EA). 

The same occurs with worm-scraper download convert scaffold zip

Note that this issue persisted after a reinstallation of worm-scraper. I also tried cding to the directory where worm-scraper was installed, to no avail.

**Comment by araphiel** [comment]
@TheIronRose 

I'm new at anything code related so bear with me.
This may not help you but I got it working via OSX:

1. Adding `#!/usr/bin/env node` to worm-scraper.js in line 1
1. Removing `/* eslint-disable no-process-exit */`

[This might be worth a look for you though](http://stackoverflow.com/questions/37192508/trying-to-execute-a-script-from-package-json-on-windows-throws-a-jscript-error)

**Comment by ChaoticWyrme** [comment]
If you run it via the node command it works, i.e
`cd %APPDATA%\npm\node_modules\worm-scraper\lib`
`node worm-scraper`

**Comment by daleamann** [comment]
> If you run it via the node command it works, i.e
> cd %APPDATA%\npm\node_modules\worm-scraper\lib
> node worm-scraper
This. Then use node before any other command

**Comment by domenic** [comment]
Sorry for the delay in fixing this; I was for some reason not watching my own repository!
