### ISSUE TITLE
line 1: use strict: command not found

### ISSUE THREAD

**Issue by mzieg** [domenic/worm-scraper#5]
FYI, on my Mac (10.12.5), after installing Node.js (6.11 LTS), worm-scraper gave this:

    $ worm-scraper --help
    /usr/local/bin/worm-scraper: line 1: use strict: command not found

Solution was to add a shebang line in worm-scraper per https://stackoverflow.com/a/34354713

**Comment by JacobJT** [comment]
For those who face this issue and want to get it working before the PR moves through,

copy this line: `#!/usr/bin/env node`

in terminal, type `vim /usr/local/bin/worm-scraper` and hit enter
Hit `shift + O` to add a new line
Hit escape
hit `shift + P` to paste
hit `:x` to save and close 

The commands should now work as expected

**Comment by domenic** [comment]
Sorry for the delay in fixing this; I was for some reason not watching my own repository!
