### ISSUE TITLE
'Not enough non-option arguments: got 0. need at least 1'

### ISSUE THREAD

**Issue by spiralll** [domenic/worm-scraper#8]
Sorry for the newbie question, but whenever I try to use one of the single letter option commands (-s, -c, -b, -o) I get the message 'Not enough non-option arguments: got 0. need at least 1.'

Could you tell me exactly what I need to type to use these commands? thanks.

**Comment by domenic** [comment]
Those are options that customize the commands. You need to actually include some commands to run. For example, run the `worm-scraper help` command for details on what available commands there are.
